import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import localFont from 'next/font/local'
import { cn } from '@/lib/utils'
import './globals.css'

const raleway = Raleway({ subsets: ['latin'], variable: '--font-raleway' })
const lufga = localFont({
  src: [
    {
      path: '../assets/fonts/lufga/thin.ttf',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../assets/fonts/lufga/thin-italic.ttf',
      weight: '100',
      style: 'italic',
    },
    {
      path: '../assets/fonts/lufga/light.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../assets/fonts/lufga/light-italic.ttf',
      weight: '200',
      style: 'italic',
    },
    {
      path: '../assets/fonts/lufga/medium.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../assets/fonts/lufga/medium-italic.ttf',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../assets/fonts/lufga/regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/lufga/regular-italic.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../assets/fonts/lufga/semibold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../assets/fonts/lufga/semibold-italic.ttf',
      weight: '600',
      style: 'italic',
    },
  ],
  variable: '--font-lufga',
})

export const metadata: Metadata = {
  title: 'Tuany Miranda Noivas & Trajes Finos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='pt-br'>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          raleway.variable,
          lufga.variable
        )}
      >
        {children}
      </body>
    </html>
  )
}
